"use client";

import React, { useState, useEffect } from "react";
import {
  Loader2,
  ArrowLeft,
  ShieldAlert,
  CheckCircle2,
  Heart,
} from "lucide-react";
import EasyCardView from "@/components/EasyCardView";
import BackgroundPattern from "@/components/BackgroundPattern";
import TetrisLoading from "@/components/ui/tetris-loader";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";

interface SharedCardPageProps {
  params: Promise<{ id: string }>;
}

export default function SharedCardPage({ params }: SharedCardPageProps) {
  const unwrappedParams = React.use(params);
  const id = unwrappedParams.id;

  const [userData, setUserData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchSharedCard = async () => {
      try {
        const res = await fetch(`/api/easy-card/public/${id}`);
        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || "Failed to load verification profile");
        }
        const data = await res.json();
        setUserData(data.user);
      } catch (err: any) {
        console.error("Shared Card Load Error:", err);
        setError(err.message || "Failed to locate health card record");
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchSharedCard();
    }
  }, [id]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-50 relative">
        <BackgroundPattern />
        <div className="relative z-10">
          <TetrisLoading
            size="lg"
            speed="normal"
            showLoadingText={true}
            loadingText="Verifying patient ID token..."
          />
        </div>
      </div>
    );
  }

  if (error || !userData) {
    return (
      <div className="flex min-h-screen items-center justify-center p-4">
        <BackgroundPattern />
        <Card className="w-full max-w-[480px] border-2 border-slate-900 shadow-xl rounded-3xl bg-white p-8 text-center flex flex-col items-center gap-6">
          <div className="w-16 h-16 rounded-full bg-rose-50 border-2 border-rose-950 flex items-center justify-center text-rose-950">
            <ShieldAlert className="h-8 w-8" />
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-extrabold text-slate-900">
              Health Card Unverified
            </h3>
            <p className="text-sm text-slate-500">
              The health identity link you accessed is invalid or has expired.
              Please verify with the patient or request a fresh shared link.
            </p>
          </div>
          <Link
            href="/"
            className="inline-flex items-center gap-2 rounded-xl px-6 py-3 font-extrabold bg-slate-900 text-white hover:bg-slate-800 border-2 border-slate-950 transition-all text-xs uppercase tracking-wider"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to MedChainify
          </Link>
        </Card>
      </div>
    );
  }

  // Construct sharing url
  const shareUrl = typeof window !== "undefined" ? window.location.href : "";

  return (
    <div className="flex min-h-screen flex-col items-center justify-center p-4 pb-16">
      <BackgroundPattern />

      <div className="w-full max-w-[900px] flex flex-col items-center gap-8 py-6">
        {/* Verification Status Header */}
        <div className="text-center space-y-2 max-w-lg">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-800 shadow-sm">
            <CheckCircle2 className="h-4 w-4 text-emerald-600 fill-emerald-50" />
            <span className="text-[9px] font-black uppercase tracking-widest">
              Verified Medical ID Summary
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900">
            {userData.name}
          </h1>
          <p className="text-xs text-slate-500">
            This read-only emergency view was generated by MedChainify using
            certified records, lab diagnostic indicators, and clinical
            prescriptions.
          </p>
        </div>

        {/* 3D Flip Card Component */}
        <div className="w-full flex justify-center">
          <EasyCardView user={userData} shareUrl={shareUrl} />
        </div>

        {/* Informative Disclaimer Card */}
        <Card className="w-full max-w-[460px] border border-slate-200 shadow-sm rounded-2xl bg-white/70 backdrop-blur-sm p-4 text-left flex gap-3">
          <Heart className="h-5 w-5 text-rose-500 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <h5 className="text-[10px] font-bold uppercase tracking-wider text-slate-700">
              Notice to Medical Responders
            </h5>
            <p className="text-[10px] text-slate-500 leading-relaxed">
              This card is a summary of the patient's record on MedChainify.
              Standard medical protocols should always be adhered to, and
              clinical markers (such as blood type or allergy status) should be
              double-checked before intervention.
            </p>
          </div>
        </Card>

        {/* Portal back button */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 rounded-xl px-5 py-2.5 font-bold bg-white text-slate-900 hover:bg-slate-50 border-2 border-slate-900 shadow-sm transition-all text-xs"
        >
          <ArrowLeft className="h-4 w-4" />
          Go to MedChainify
        </Link>
      </div>
    </div>
  );
}
